import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations = {
  ar: {
    'home': 'الرئيسية',
    'search_placeholder': 'ما الذي تبحث عنه اليوم؟',
    'search_results': 'نتائج البحث',
    'account': 'حسابي',
    'favorites': 'المفضلة',
    'cart': 'الحقيبة',
    'categories': 'الأقسام',
    'browse_categories': 'تصفح حسب التصنيف',
    'new_arrivals': 'وصل حديثاً',
    'shop_now': 'تسوق الآن',
    'support': 'الدعم',
    'share': 'مشاركة',
    'language_country': 'اللغة والبلد',
    'yemen_arabic': 'اليمن / العربية',
    'uae_english': 'الإمارات / English',
    'settings': 'الإعدادات',
    'privacy_policy': 'سياسة الخصوصية',
    'contact_us': 'اتصل بنا',
    'about_tamtom': 'عن طمطوم',
    'orders': 'طلباتي',
    'logout': 'تسجيل الخروج',
    'login': 'دخول',
    'register': 'تسجيل',
    'add_to_cart': 'إضافة للسلة',
    'currency': 'ر.ي',
    'whatsapp': 'واتساب',
    'direct_call': 'اتصال مباشر',
    'how_can_we_help': 'كيف يمكننا مساعدتك؟',
    'we_are_here': 'نحن متواجدون لخدمتك في أي وقت',
    'total': 'الإجمالي',
    'checkout': 'إتمام الطلب',
    'empty_cart': 'سلتك فارغة',
    'empty_favorites': 'قائمة المفضلة فارغة',
    'start_shopping': 'ابدأ التسوق الآن',
    'delivery': 'التوصيل',
    'fresh_daily': 'طازج يومياً',
    'exclusive_offers': 'عروض حصرية',
    'best_selling': 'الأكثر مبيعاً',
    'new_product': 'منتج جديد',
    'available': 'متوفر',
    'out_of_stock': 'غير متوفر',
    'price': 'السعر',
    'quantity': 'الكمية',
    'rating': 'التقييم',
    'reviews': 'التقييمات',
    'seller': 'البائع',
    'special_offers': 'العروض الخاصة',
    'discount': 'خصم',
    'save': 'حفظ',
    'delete': 'حذف',
    'edit': 'تعديل',
    'cancel': 'إلغاء',
    'confirm': 'تأكيد',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'نجاح',
    'warning': 'تحذير',
    'info': 'معلومات',
    'yes': 'نعم',
    'no': 'لا',
    'name': 'الاسم',
    'email': 'البريد الإلكتروني',
    'phone': 'رقم الهاتف',
    'address': 'العنوان',
    'country': 'الدولة',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'remember_me': 'تذكرني',
    'forgot_password': 'هل نسيت كلمة المرور؟',
    'create_account': 'إنشاء حساب جديد',
    'sign_in': 'تسجيل الدخول',
    'profile': 'الملف الشخصي',
    'my_orders': 'طلباتي',
    'order_history': 'سجل الطلبات',
    'delivery_address': 'عنوان التوصيل',
    'payment_method': 'طريقة الدفع',
    'order_total': 'إجمالي الطلب',
    'estimated_delivery': 'الوقت المتوقع للتوصيل',
    'order_status': 'حالة الطلب',
    'pending': 'قيد الانتظار',
    'processing': 'جاري المعالجة',
    'shipped': 'تم الشحن',
    'delivered': 'تم التسليم',
    'cancelled': 'تم الإلغاء',
    'must_login_first': 'يجب تسجيل الدخول أولاً',
    'data_saved': 'تم حفظ البيانات',
    'profile_updated_success': 'تم تحديث معلومات الملف الشخصي بنجاح',
    'save_error': 'خطأ في الحفظ',
    'update_error_try_again': 'حدث خطأ أثناء تحديث البيانات. يرجى المحاولة مرة أخرى.',
    'loading_data': 'جاري تحميل البيانات...',
    'data_saved_locally': 'تم حفظ البيانات محلياً',
    'guest_save_description': 'تم حفظ معلوماتك محلياً. للحفظ الدائم، يمكنك تسجيل حساب جديد.',
    'local_save_error': 'حدث خطأ أثناء حفظ البيانات محلياً',
    'total_orders': 'إجمالي الطلبات',
    'member_since': 'عضو منذ',
    '6_months': '6 أشهر',
    'view_order_history': 'عرض تاريخ الطلبات',
    'all_categories': 'كل التصنيفات',
    'offers': 'العروض',
    'delivery_app': 'تطبيق الدلفري',
    'switch_to_driver_app': 'انتقال إلى تطبيق السائقين',
    'saved_addresses': 'العناوين المحفوظة',
    'manage_delivery_addresses': 'إدارة عناوين التوصيل',
    'app_and_account_settings': 'إعدادات التطبيق والحساب',
    'whatsapp_support': 'دعم واتساب',
    'contact_us_via_whatsapp': 'تواصل معنا عبر واتساب',
    'call_us': 'اتصل بنا',
    'call_direct_support': 'اتصل برقم الدعم المباشر',
    'share_app': 'مشاركة التطبيق',
    'share_with_friends': 'شارك التطبيق مع أصدقائك',
    'copy_link': 'نسخ الرابط',
    'privacy_and_terms': 'سياسة الخصوصية وشروط الاستخدام',
    'guest_user': 'مستخدم ضيف',
    'user': 'المستخدم',
    'premium_member': 'عضو مميز',
    'saving': 'جاري الحفظ...',
    'save_locally': 'حفظ محلياً',
    'save_changes': 'حفظ التغييرات',
    'edit_info': 'تعديل المعلومات',
    'failed_to_fetch_orders': 'فشل في جلب الطلبات',
    'unknown_restaurant': 'مطعم غير معروف',
    'reordering': 'جاري إعادة الطلب',
    'reorder_description': 'سيتم إضافة عناصر طلب {orderNumber} إلى السلة',
    'all_orders': 'جميع الطلبات',
    'active': 'النشطة',
    'completed': 'المكتملة',
    'loading_your_orders': 'جاري تحميل طلباتك...',
    'error_loading_orders': 'حدث خطأ في تحميل الطلبات',
    'retry': 'إعادة المحاولة',
    'track_and_review_orders': 'تتبع ومراجعة طلباتك',
    'no_orders': 'لا توجد طلبات',
    'no_orders_yet': 'لم تقم بأي طلبات بعد',
    'start_ordering_now': 'ابدأ الطلب الآن',
    'order_no': 'طلب رقم',
    'no_items_details': 'لا توجد تفاصيل العناصر',
    'items_count': 'عدد الأصناف',
    'order_date': 'تاريخ الطلب',
    'estimated_time': 'الوقت المتوقع',
    'payment': 'الدفع',
    'cash': 'نقدي',
    'online': 'إلكتروني',
    'track_order': 'تتبع الطلب',
    'reorder': 'إعادة الطلب',
    'loading_order_details': 'جاري تحميل بيانات الطلب...',
    'error_finding_order': 'تعذر العثور على بيانات الطلب. قد يكون المعرف غير صحيح.',
    'back_to_home': 'العودة للرئيسية',
    'estimated_time_desc': 'الوقت المتوقع',
    'restaurant': 'المطعم',
    'delivery_driver': 'سائق التوصيل',
    'delivering': 'جاري التوصيل',
    'call': 'اتصال',
    'driver_on_way': 'السائق في الطريق إليك',
    'order_details': 'تفاصيل الطلب',
    'order_timeline': 'تاريخ الطلب',
    'no_updates_available': 'لا توجد تحديثات متاحة حالياً',
    'contact_support': 'تواصل مع الدعم',
    'cancel_order': 'إلغاء الطلب',
    'order_no_prefix': 'طلب #',
  },
  en: {
    'home': 'Home',
    'search_placeholder': 'What are you looking for today?',
    'search_results': 'Search Results',
    'account': 'Account',
    'favorites': 'Favorites',
    'cart': 'Cart',
    'categories': 'Categories',
    'browse_categories': 'Browse by Category',
    'new_arrivals': 'New Arrivals',
    'shop_now': 'Shop Now',
    'support': 'Support',
    'share': 'Share',
    'language_country': 'Language & Country',
    'yemen_arabic': 'Yemen / Arabic',
    'uae_english': 'UAE / English',
    'settings': 'Settings',
    'privacy_policy': 'Privacy Policy',
    'contact_us': 'Contact Us',
    'about_tamtom': 'About Tamtom',
    'orders': 'My Orders',
    'logout': 'Logout',
    'login': 'Login',
    'register': 'Register',
    'add_to_cart': 'Add to Cart',
    'currency': 'SAR',
    'whatsapp': 'WhatsApp',
    'direct_call': 'Direct Call',
    'how_can_we_help': 'How can we help?',
    'we_are_here': 'We are here to help you anytime',
    'total': 'Total',
    'checkout': 'Checkout',
    'empty_cart': 'Your cart is empty',
    'empty_favorites': 'Your favorites list is empty',
    'start_shopping': 'Start Shopping Now',
    'delivery': 'Delivery',
    'fresh_daily': 'Fresh Daily',
    'exclusive_offers': 'Exclusive Offers',
    'best_selling': 'Best Selling',
    'new_product': 'New Product',
    'available': 'Available',
    'out_of_stock': 'Out of Stock',
    'price': 'Price',
    'quantity': 'Quantity',
    'rating': 'Rating',
    'reviews': 'Reviews',
    'seller': 'Seller',
    'special_offers': 'Special Offers',
    'discount': 'Discount',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Information',
    'yes': 'Yes',
    'no': 'No',
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone Number',
    'address': 'Address',
    'country': 'Country',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'remember_me': 'Remember Me',
    'forgot_password': 'Forgot Password?',
    'create_account': 'Create New Account',
    'sign_in': 'Sign In',
    'profile': 'Profile',
    'my_orders': 'My Orders',
    'order_history': 'Order History',
    'delivery_address': 'Delivery Address',
    'payment_method': 'Payment Method',
    'order_total': 'Order Total',
    'estimated_delivery': 'Estimated Delivery Time',
    'order_status': 'Order Status',
    'pending': 'Pending',
    'processing': 'Processing',
    'shipped': 'Shipped',
    'delivered': 'Delivered',
    'cancelled': 'Cancelled',
    'must_login_first': 'You must login first',
    'data_saved': 'Data Saved',
    'profile_updated_success': 'Profile updated successfully',
    'save_error': 'Save Error',
    'update_error_try_again': 'An error occurred while updating. Please try again.',
    'loading_data': 'Loading data...',
    'data_saved_locally': 'Data saved locally',
    'guest_save_description': 'Your info is saved locally. For permanent save, create an account.',
    'local_save_error': 'Error saving data locally',
    'total_orders': 'Total Orders',
    'member_since': 'Member since',
    '6_months': '6 months',
    'view_order_history': 'View order history',
    'all_categories': 'All Categories',
    'offers': 'Offers',
    'delivery_app': 'Delivery App',
    'switch_to_driver_app': 'Switch to Driver App',
    'saved_addresses': 'Saved Addresses',
    'manage_delivery_addresses': 'Manage delivery addresses',
    'app_and_account_settings': 'App and account settings',
    'whatsapp_support': 'WhatsApp Support',
    'contact_us_via_whatsapp': 'Contact us via WhatsApp',
    'call_us': 'Call Us',
    'call_direct_support': 'Call direct support',
    'share_app': 'Share App',
    'share_with_friends': 'Share with friends',
    'copy_link': 'Copy Link',
    'privacy_and_terms': 'Privacy Policy and Terms',
    'guest_user': 'Guest User',
    'user': 'User',
    'premium_member': 'Premium Member',
    'saving': 'Saving...',
    'save_locally': 'Save Locally',
    'save_changes': 'Save Changes',
    'edit_info': 'Edit Information',
    'failed_to_fetch_orders': 'Failed to fetch orders',
    'unknown_restaurant': 'Unknown Restaurant',
    'reordering': 'Reordering...',
    'reorder_description': 'Adding items from order {orderNumber} to cart',
    'all_orders': 'All Orders',
    'active': 'Active',
    'completed': 'Completed',
    'loading_your_orders': 'Loading your orders...',
    'error_loading_orders': 'Error loading orders',
    'retry': 'Retry',
    'track_and_review_orders': 'Track and review your orders',
    'no_orders': 'No orders',
    'no_orders_yet': 'You haven\'t made any orders yet',
    'start_ordering_now': 'Start ordering now',
    'order_no': 'Order No',
    'no_items_details': 'No item details',
    'items_count': 'Items Count',
    'order_date': 'Order Date',
    'estimated_time': 'Estimated Time',
    'payment': 'Payment',
    'cash': 'Cash',
    'online': 'Online',
    'track_order': 'Track Order',
    'reorder': 'Reorder',
    'loading_order_details': 'Loading order details...',
    'error_finding_order': 'Could not find order data. ID may be incorrect.',
    'back_to_home': 'Back to Home',
    'estimated_time_desc': 'Estimated Time',
    'restaurant': 'Restaurant',
    'delivery_driver': 'Delivery Driver',
    'delivering': 'Delivering',
    'call': 'Call',
    'driver_on_way': 'Driver is on the way to you',
    'order_details': 'Order Details',
    'order_total': 'Order Total',
    'order_timeline': 'Order Timeline',
    'no_updates_available': 'No updates available currently',
    'contact_support': 'Contact Support',
    'cancel_order': 'Cancel Order',
    'order_no_prefix': 'Order #',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLangState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    const direction = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = direction;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['ar']] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
